### ISSUE TITLE
Late binding of certificates and @signs for improved experience for new @signs

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#157]
Create pool of certificates and DNS records and bind them to an @sign once activated.
Improves onboarding and registrar website

- [x]  Document solution - @cconstab
https://docs.google.com/presentation/d/1LhVKrSXE8grevhW-AiTmt9LEpDAUkXeBdXWT9bDgiOo/edit#slide=id.p
- [ ] 1. Break create(shell script) for SSL generation and Secondaries.
- [ ] 2. Refactor create the script for SSL and secondary base path.
- [ ] 3. Refactor cert gen script to accept parameters.
- [ ] 4. Work with the Dev team for integration.
- [ ] 5. Changes in registrar app

**Comment by cpswan** [comment]
Moved back to backlog as this may not be needed in light of faster cert issue and ability to parallelise cert generation with API based scripts.

**Comment by cpswan** [comment]
This is back in the frame due to issues experienced with ZeroSSL outage causing #340

**Comment by athandle** [comment]
Mentioned below is an approach for SSL late binding 

1. Generate X no. of SSL and maintain a pool
2. When new activation requests come start secondary and map the SSL
3. After successful activation generate SSL to maintain the pool
4. SSL renewal process will remain the same as it's now, will keep on renewing SSLs if in case they are not used

**Instead of complete re-write, we will break the current script into 2** 

1. Generate SSL
2. Map SSL and start secondary


Mongo will maintain a pool of UUIDs where we have SSL ready when the new request will come Mongo will give UUID, atsign, port to start secondary

Note: Fall back mechanism to Letsencrypt we have to discuss with Chris as he started on this task(assumption)
Another approach that we discussed to maintain SSLs in Mongo, will increase overhead for renewal etc.

@cpswan @cconstab let us know your thoughts

**Comment by cpswan** [comment]
Sounds like a good plan.

I'd like to use my new Python script for SSL key generation using the ACME interface at LetsEncrypt or ZeroSSL. We can then have failover logic if one of the CAs isn't working.

**Comment by athandle** [comment]
@cpswan sounds good @kumarnarendra701  can you please check Chris script and use it as base line

**Comment by cpswan** [comment]
@kumarnarendra701 you'll find the ACME script at https://github.com/atsign-foundation/at_virtual_environment/blob/trunk/automation/acme_certs.py

**Comment by ksanty** [comment]
@cpswan and @cconstab is the top checklist still accurate?

**Comment by athandle** [comment]
@ksanty nope, will update soon

**Comment by kumarnarendra701** [comment]
@athandle @cpswan - Please find below updates -
1. Split of the script(Cert generation and secondaries creation) - Completed
2. K8 secrete creation for the new script - Completed
3. K8 Deployment update - Completed.
4. Docker file update for symlink - Completed.

**Comment by ksanty** [comment]
Need an architecture call discussion. Quicker feedback from @kumarnarendra701 please.

**Comment by kumarnarendra701** [comment]
@ksanty @cpswan  - POC of late binding completed with the current script, now working on a new python script to get SSL with failover.

**Comment by kumarnarendra701** [comment]
@cpswan -  Modified code to generate SSL on the respective directory and raised PR for that. Please review and share your feedback and also need to understand the renewal process because earlier we had ".vald" file where the expiry timestamp was there and by using that below script take care of the renewal process.
https://github.com/atsign-company/secondaries-scripts/blob/master/cert_ren.sh

**Comment by kumarnarendra701** [comment]
@cpswan - Updated code and commented on PR review.
https://github.com/atsign-company/secondaries-scripts/tree/feature/split-ssl/sec-split-ssl

**Comment by kumarnarendra701** [comment]
@cpswan - Changes are live on buzz and verified a few SSL/Secondaries creations.

**Comment by cpswan** [comment]
Almost there with this one. Re-estimating to 2SP for prod changes.

**Comment by kumarnarendra701** [comment]
@cpswan
Deployed code on buzz and It seems working fine in buzz. We are planning to go live on prod.
Changes for Prod -
1. Script sync.
2. Node API deployment.

**Comment by kumarnarendra701** [comment]
@cpswan - 
1. Script and Node API deployed on production.
2. Letsencrypt SSL failure alert configured on Buzz and prod.
@athandle - Please let me know once you are done with testing will make it a new script primary.

**Comment by cpswan** [comment]
@kumarnarendra701 @athandle can this ticket be closed now?

**Comment by athandle** [comment]
@cpswan Narendra work is almost done, it's just a matter of updating .env but I was holding this ticket as I was waiting for confirmation on 
https://github.com/atsign-company/at_handle_registrar_web/issues/239

**Comment by athandle** [comment]
@cpswan  this is done on prod, we can close
