### ISSUE TITLE
Uncaught Socket exceptions. 

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#1689]
### Describe the bug

Whilst investigating a socket error in some personal code and looking at the atServer code to see how we caught the exception, it seems from the logs we also crash. However I now do not think it is a fatal crash.
Here is are some sample log file entries

```
d8f88b04-3047-5ec3-ba81-3c65f62764dd_secondary.1.ppbsp8gwt6em@canary-03.us-central1-c.c.secondaries.internal    | SEVERE|2023-12-05 00:31:19.268232|OutboundMessageListener|SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 104), address = 2ffeca71-aaad-52d1-ba55-9173d5504f1f.swarm0002.atsign.zone, port = 42152
d8f88b04-3047-5ec3-ba81-3c65f62764dd_secondary.1.ppbsp8gwt6em@canary-03.us-central1-c.c.secondaries.internal    | SEVERE|2023-12-05 00:31:19.269954|SecondaryServerBootStrapper|Uncaught error: SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 104), address = 2ffeca71-aaad-52d1-ba55-9173d5504f1f.swarm0002.atsign.zone, port = 42152
```

This would seem to suggest that we have a SocketException but it is not being caught by either binding or the socket itself.

I see the same thing with my test code located at:-

https://github.com/atsign-company/Colin-snippets/blob/master/socket-listener/bin/socket_listener.dart

This code does not crash but a simple nmap upsets it.

### Steps to reproduce

1. First I run the code at https://github.com/atsign-company/Colin-snippets/blob/master/socket-listener/bin/socket_listener.dart
2. Then I run a nmap scan
3. And then I see the crash
4. I cannot seem to catch the SocketException in the main loop so I have had to runZoneGuarded

### Expected behavior

The SocketException should just get caught and things just move along ? Why the unCaught Exception up to main?

### Screenshots

See the software running in a three windows and 'crash' when a port scan is run....

https://asciinema.org/a/fTtlBiZnHeCmFPxNeffw7mc90

**Comment by gkc** [comment]
@cconstab I'm not seeing evidence of a crash in the logs you provided; but I can see that the secondarybootstrapper is handling an otherwise-uncaught error and therefore it looks like the server is not crashing - but I can see in the code that it will result in a soft restart 

This scenario is useful for discovering how the error is slipping through and I will investigate - thanks!

**Comment by cconstab** [comment]
Yup I updated the decription when I saw the same non crash but escaping Exxeption.. 

I originally did not have the main wrapped in my code.

Its interesting in any case.

**Comment by gkc** [comment]
@cconstab See https://github.com/atsign-company/Colin-snippets/pull/17

**Comment by cconstab** [comment]
Perfect catch thank you..

**Comment by gkc** [comment]
@cconstab Do you know how to reproduce this on your atServer? Running nmap in itself isn't enough (at least, for me)

**Comment by cconstab** [comment]
I do not. I suspect a timing issue also hence running the test bed locallly and scanning, as its super intermittent in the real world.

**Comment by gkc** [comment]
After some further testing I've proven that the problem is that, when we write data onto sockets in the secondary server, we do not subsequently call flush(). Per documentation of dart.io's IOSink interface
```
  /// This operation is non-blocking. See [flush] or [done] for how to get any
  /// errors generated by this call.
  void write(Object? object);
```

As a result, if the socket has been closed (for example by the other end) then the call to write() does not itself throw an exception, but an exception is thrown asynchronously shortly afterwards.

There are two things to do
1. Update the interfaces and implementations of the `write` method in classes/interfaces which wrap sockets in some way (InboundConnection, OutboundConnection et al) from `void write(String data);` to `Future<void> write(String data);` and update any code which calls that method accordingly.
2. Ensure that for every socket connection made we have a block of code like `socket.done.onError(() {// connection clean-up code});
