### ISSUE TITLE
Need to comment SIGTERM related code to run atserver locally on windows.

### ISSUE THREAD

**Issue by vnaresh66** [atsign-foundation/at_server#1946]
### Describe the bug

While trying to run the secondary server Need to comment SIGTERM related code to run atserver locally on windows.

### Steps to reproduce

The code is being run on the windows machine
1.Clone the at_server
2. open packages/at_secondary_server/lib.srcbootstrapper.dart file
3. uncomment the line numbers 66, 67 
![SIGTERM_issue](https://github.com/atsign-foundation/at_server/assets/26575857/523c2bd1-3067-444a-8a5c-88235b342fa7)

@murali-shris , @sitaram-kalluri 

### Expected behavior

Need to connect to the secondary server with SIGTERM configuration enabled.

### Screenshots

![SIGTERM_issue](https://github.com/atsign-foundation/at_server/assets/26575857/1b5470ed-64cf-443a-a8e8-ca23bd6c2e17)

### Smartphones

My windows configuration is
Windows 10 Pro
64 bit machine
2 core processor

### Were you using an atApplication when the bug was found?

no

**Comment by cpswan** [comment]
We just discussed this on the arch call, and the consensus was that we're not going to take on the additional support burden of another platform.

So won't fix for this specific issue.

@vnaresh66 can you please get WSL2 setup on your Windows machine with a recent Ubuntu LTS distribution (22.04 or 24.04) so that can be used for your local builds and testing.
