### ISSUE TITLE
Migrate existing secondaries to new SSL generation script

### ISSUE THREAD

**Issue by athandle** [atsign-foundation/at_server#232]
- Buzz
- Hornet

Production plan

- [ ] Move code to production
- [ ]

**Comment by kumarnarendra701** [comment]
Created migration script for secondaries migration to support new SSL structure and renewal.
Script location - /gluster/@/api/ssl-stack-upgrade.sh

**Comment by kumarnarendra701** [comment]
@cpswan - Please review script 
https://github.com/atsign-company/secondaries-scripts/pull/3
Migration script - https://github.com/atsign-company/secondaries-scripts/blob/dev/ssl-stack-upgrade.sh

**Comment by cpswan** [comment]
@kumarnarendra701 I'm seeing a couple of typos in that script:

> log='**secoundaries**-logs/create/'$UUID'-create_log.txt'

> echo "**Secondarie** migration started" >> $log 2>&1

> **secoundary**_full_path=$(find /gluster/@/secondaries/ -name "$UUID" -print)

etc.

I also don't understand the purpose of:

> for UUID in cd92e589-5e64-5aae-a0e2-b146f9dcccce

and

> sed -i '23d' $secoundary_full_path/docker-compose.yml

**Comment by kumarnarendra701** [comment]
Below stacks updated.
ebf8e6fe-843b-5b90-80af-08751bdf706b
ec2d09ed-278c-5ba1-9a16-1fcf36b1a7b7
ec5c8070-995c-5a6a-be24-351367f265e8
ec64e9df-d401-54e5-ac5a-7d166e4ec56d
ed4fc729-013e-570a-a5a1-7623e60d9268
ed7b0437-3b93-5cae-b980-9927355154f3
ed12c4f8-db07-56ca-8c0b-043326f3405e
ed32b5c2-50de-5a7e-b134-312561a35c5b
ed7112f5-5b7b-5f5b-9d13-660349949e17
edee6974-784e-5d55-9c72-2ac199b7b365

@kalluriramkumar - Please verify the below stacks.

**Comment by sitaram-kalluri** [comment]
> Below stacks updated.
> ebf8e6fe-843b-5b90-80af-08751bdf706b
> ec2d09ed-278c-5ba1-9a16-1fcf36b1a7b7
> ec5c8070-995c-5a6a-be24-351367f265e8
> ec64e9df-d401-54e5-ac5a-7d166e4ec56d
> ed4fc729-013e-570a-a5a1-7623e60d9268
> ed7b0437-3b93-5cae-b980-9927355154f3
> ed12c4f8-db07-56ca-8c0b-043326f3405e
> ed32b5c2-50de-5a7e-b134-312561a35c5b
> ed7112f5-5b7b-5f5b-9d13-660349949e17
> edee6974-784e-5d55-9c72-2ac199b7b365
> 
> @kalluriramkumar - Please verify the below stacks.

@kumarnarendra701 : Verified the logs of above stacks, For the stack 'ebf8e6fe-843b-5b90-80af-08751bdf706b' observed the below error message. Please confirm if the issue is resolved.

ebf8e6fe-843b-5b90-80af-08751bdf706b_secondary.1.jbqspo7k1p9r@buzz-02    | SEVERE|2021-07-28 23:30:00.035244|AtCompactionJob|Instance of 'AtAccessLog' s
tarting 
ebf8e6fe-843b-5b90-80af-08751bdf706b_secondary.1.zq9h1j39mfj8@buzz-02    | #0      _RandomAccessFile.lock.<anonymous closure> (dart:io/file_impl.dart:999)
ebf8e6fe-843b-5b90-80af-08751bdf706b_secondary.1.jbqspo7k1p9r@buzz-02    | 
ebf8e6fe-843b-5b90-80af-08751bdf706b_secondary.1.zq9h1j39mfj8@buzz-02    | <asynchronous suspension>
ebf8e6fe-843b-5b90-80af-08751bdf706b_secondary.1.jbqspo7k1p9r@buzz-02    | SEVERE|2021-07-28 23:45:00.036646|AtCompactionJob|Instance of 'AtAccessLog' s
ebf8e6fe-843b-5b90-80af-08751bdf706b_secondary.1.zq9h1j39mfj8@buzz-02    | #1      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:81)
tarting 
ebf8e6fe-843b-5b90-80af-08751bdf706b_secondary.1.zq9h1j39mfj8@buzz-02    | <asynchronous suspension>
ebf8e6fe-843b-5b90-80af-08751bdf706b_secondary.1.jbqspo7k1p9r@buzz-02    | 
ebf8e6fe-843b-5b90-80af-08751bdf706b_secondary.1.zq9h1j39mfj8@buzz-02    | #2      HiveImpl._openBox (package:hive/src/hive_impl.dart:116)
ebf8e6fe-843b-5b90-80af-08751bdf706b_secondary.1.jbqspo7k1p9r@buzz-02    | SEVERE|2021-07-29 00:00:00.001768|AtCompactionJob|Instance of 'AtAccessLog' s
ebf8e6fe-843b-5b90-80af-08751bdf706b_secondary.1.zq9h1j39mfj8@buzz-02    | <asynchronous suspension>
tarting 
ebf8e6fe-843b-5b90-80af-08751bdf706b_secondary.1.zq9h1j39mfj8@buzz-02    | #3      HiveImpl.openBox (package:hive/src/hive_impl.dart:145)
ebf8e6fe-843b-5b90-80af-08751bdf706b_secondary.1.jbqspo7k1p9r@buzz-02    | 
ebf8e6fe-843b-5b90-80af-08751bdf706b_secondary.1.zq9h1j39mfj8@buzz-02    | 
ebf8e6fe-843b-5b90-80af-08751bdf706b_secondary.1.zq9h1j39mfj8@buzz-02    | <asynchronous suspension>
ebf8e6fe-843b-5b90-80af-08751bdf706b_secondary.1.zq9h1j39mfj8@buzz-02    | #4      CommitLogKeyStore.init (package:at_persistence_secondary_server/src/log/commitlog/commit_log_keystore.dart:31)
ebf8e6fe-843b-5b90-80af-08751bdf706b_secondary.1.jbqspo7k1p9r@buzz-02    | SEVERE|2021-07-29 00:15:00.025801|AtCompactionJob|Instance of 'AtAccessLog' s
ebf8e6fe-843b-5b90-80af-08751bdf706b_secondary.1.zq9h1j39mfj8@buzz-02    | <asynchronous suspension>

**Comment by kumarnarendra701** [comment]
@kalluriramkumar - As discussed below stacks updated, please verify and confirm so that we can proceed with all buzz upgrades.
1. odd15
2. violetred7ready)

**Comment by athandle** [comment]
@kalluriramkumar  any update on this?

**Comment by sitaram-kalluri** [comment]
> @kalluriramkumar any update on this?

Shared persona's between the odd15 and violetred7ready atsign's in the buzz environment. and is working successfully.
Attaching the test log below.
![Image-1](https://user-images.githubusercontent.com/16645698/128051202-7865786d-a670-4119-8f4c-96f19d6ae603.png)
![Image-2](https://user-images.githubusercontent.com/16645698/128051723-6ca0d8a5-823a-478d-8e00-ef75bb495f1e.png)

**Comment by murali-shris** [comment]
@athandle is there any pending work on this issue.Can it be closed ?

**Comment by athandle** [comment]
@murali-shris  we are migrating all buzz atsigns to new method, once migrated we will move the changes to prod. 
And then we will migrate over there, I think then only we can close this ticket

**Comment by athandle** [comment]
@cpswan all atsigns are migrated to new APIs. Please confirm when we can go live on hornet

**Comment by cpswan** [comment]
@athandle please proceed with Hornet

**Comment by athandle** [comment]
@kalluriramkumar @murali-shris @cpswan @cconstab 
Note from Narendra:
I have moved the new SSL bash version script to the prod(/gluster/@/new-api) and modify all changes and was able to create and delete secondary but facing issue with SSL renewal that I had reported during buzz migration, renewal script creating a restart file in SSL directory but not getting restarted.

To reproduce the issue - 
1. Login Hornet5 server and create restart inside  "/etc/letsencrypt/live/fca6c8ce-4692-589c-b4be-a549f1420711.hornet.atsign.zone"
2. Check for docker logs - "docker logs -f d65d784a78c7"

**Comment by athandle** [comment]
@cpswan @cconstab 
@kalluriramkumar any update on this?

**Comment by sitaram-kalluri** [comment]
Tried connecting to Hornet-05 server using below command:

sitaram@sitaram-ThinkPad-E14:~$ gcloud beta compute ssh --zone "us-central1-a" "hornet-05" --project "secondaries"
ERROR: (gcloud.beta.compute.ssh) Could not fetch resource:
 - The resource 'projects/secondaries/zones/us-central1-a/instances/hornet-05' was not found

Need help on connecting to hornet-5 server.

**Comment by cpswan** [comment]
@kalluriramkumar the correct command to connect to Hornet-05 is:

```bash
gcloud compute ssh hornet-05 --zone "us-central1-b" --project "secondaries"
```

No need for `beta` and the Hornet instances are spread across the zones within the us-central1 region, so it's worth doing a `gcloud compute instances list` to see where they are.

**Comment by ksanty** [comment]
@kumarnarendra701 can you please add [label(s)](https://github.com/atsign-company/labels/labels) to this, so we can better track?  TY

**Comment by kumarnarendra701** [comment]
Dependent on #267

**Comment by cpswan** [comment]
@kumarnarendra701 has stated that the new scripts are now deployed to prod.
