### ISSUE TITLE
Investigate use of Melos for dependency overrides

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#374]
**Describe the solution you'd like**
See if [Melos](https://github.com/invertase/melos) can help us (and maybe replace our Python scripts)

**Comment by Salakar** [comment]
👋 melos maintainer here, let me know if there's anything I can help with or any questions I can answer. Thanks

**Comment by sitaram-kalluri** [comment]
@salakar, thanks very much for the offer to help. I do have a question:

Does Melos support adding the dependent packages from git repositories under dependency overrides in pubspec.yaml?  

Our application has 8 packages which are divided among 4 git repositories. When running automated tests in GitHub Actions the changes in the dependent packages need to be propagated into the top level packages. At the moment, we are manually updating the dependency overrides section in the pubspec.yaml of the top level package with the git references of the dependent packages. Can you please let me know if melos helps in solving the problem of manually overriding the pubspec.yaml? If not already available any plans in future?

**Comment by Salakar** [comment]
Sorry I missed your reply. It currently does not support defining global dependency overrides and it only overrides for packages that exist within the workspace (there's also a PR in progress that allows symlinks too), e.g. if package `a` exists in the workspace then all other packages in the workspace that depend on `a` will get an override.

It should be a relatively trivial feature to add though since all the internals exist already, would you mind adding a feature request issue and I'll take a look?

**Comment by cpswan** [comment]
Closing this as we've ended up using Melos for at_mono
