### ISSUE TITLE
reduce compaction interval to 1 hr in staging

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#399]
override the below config value in staging servers.

prod value:
compactionFrequencyMins: 720

staging value:
compactionFrequencyMins: 60

Secondaries in staging to deploy the changes:
disastrousspacedisco,gorgeouskicking, violetred7ready, colin

**Comment by kumarnarendra701** [comment]
@murali-shris - Added ENV for disastrousspacedisco,gorgeouskicking, violetred7ready, colin

#docker inspect aba8f35b8ce4
"Env": [
    "compactionFrequencyMins=60",
    
Please verify and confirm.

**Comment by murali-shris** [comment]
@kumarnarendra701 we are unable to verify the changes in staging since our latest code is not deployed to staging. There is an issue with incorrect docker image deployed to staging.
Below update from Chris:
But on staging I see sha256:b65fecae2a35459caf88c6c3728cb54349c143470155d43406f7e60dac1263b6 for the latest amd64 dev_env on DockerHub but "Image": "reg.buzz.do-sf2.atsign.zone/atsigncompany/secondary:dev_env@sha256:e38825432a07715506fd42246eda2d17171a90250184600f4c6952ae9d9c86c6" running on @colin 

The weird thing is that there's no sign of sha256:e38825432... on DockerHub (or the previous sha256:9f14ab92f6...

**Comment by cpswan** [comment]
@kumarnarendra701 if we modify some (or all) of the staging secondaries to mount /atsign/storage rather than /atsign (per #296) then we'll be able to see the version numbers in logs and clear up whether we're running what we expect to be running.

@murali-shris I can do this now for disastrousspacedisco, gorgeouskicking, violetred7ready, colin if that helps?

**Comment by cpswan** [comment]
@murali-shris I've redone the mount points for disastrousspacedisco, gorgeouskicking, violetred7ready & colin so that we can see the version number from pubspec.yaml.

The logs from @ colin confirm that we're running the image built by GitHub Actions run [400](https://github.com/atsign-foundation/at_server/actions/runs/1475227692) (the most recent merge from trunk):

```
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.pk6x6tsd3v64@buzz-02    | INFO|2021-11-18 11:54:04.624196|AtSecondaryServer|Secondary server started on version : 3.0.8+gha400 on root server : root.atsign.wtf
```

**Comment by murali-shris** [comment]
reduced the compaction interval to 1hr in config file
