### ISSUE TITLE
Modify registrar to create secondaries on newly added clusters

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#485]
Lead: @athandle 

**Is your feature request related to a problem? Please describe.**
Secondaries are only created on Hornet at the moment

**Describe the solution you'd like**
As we create new clusters these should be targetable once we determine that existing clusters are full.

**Comment by athandle** [comment]
@cpswan can I assume we have to shut down old and start using new?
please share domain for buzz and blocked ports

**Comment by cpswan** [comment]
@athandle For now we won't be adding extra dev/staging clusters, just prod.

I think it is OK to assume that we won't be creating new secondaries in old clusters (and if we need to migrate/rebalance that will happen outside of the provisioning process).

**Comment by athandle** [comment]
@cpswan  can we test this first on dev as code was written year ago and was never tested. If we don't have that leverage then please confirm.

**Comment by cpswan** [comment]
@athandle Could we use the Canary cluster to test?

**Comment by athandle** [comment]
I think yes @kumarnarendra701  can you confirm

**Comment by cconstab** [comment]
icon for webhook
![canary](https://user-images.githubusercontent.com/6131216/150865271-936f5700-0ee1-4489-b494-f08f0c2342fe.png)

**Comment by athandle** [comment]
@cpswan it's not working on dev environment, I will check on prod over weekend

**Comment by cpswan** [comment]
@athandle I'm not sure what you're saying isn't working. Can you please provide a more detailed description?

**Comment by athandle** [comment]
@cpswan I tried to check by just updating the domain of canary on dev it didn't work, Once our current hackathons are done and we have some window I will test directly on prod. Hardly 1 minute. Hopefully over the weekend.

Before that, I want to check with Narendra also if he knows any glitches because this code was written a year back and many things changed after that. That's why I was thinking to test on dev.

**Comment by cpswan** [comment]
@athandle I'd like to understand *why* it's not working? Likely to be naming or permissions, but let's figure it out.

**Comment by kumarnarendra701** [comment]
@athandle - It seems you are trying to generate secondary with "canary.atsign.zone" like UUID.canary.atsign.zone but it will not work because we have Domain variable hardcoded in Shell script and generating SSL and Domain mapping for "buzz.do-sf2.atsign.zone". If our plan is to handle both domains in the script then we need to put conditions for DNS map and SSL creation.
@cpswan - Please share your thoughts if you see any other way to handle this.

**Comment by cpswan** [comment]
@kumarnarendra701 I think this has a dependency on #484 I've already started work on that, but I'll make it my priority for the next few days. It will help me out to have a full list of scripts that need to be run.

Part of the work is already in place, namely the `create_cert_md.sh` in `/gluster/@/api`, though I'd like to get that folded back into `create_cert.sh`

**Comment by cpswan** [comment]
There are now _md versions of all the key scripts that can be used for testing whilst https://github.com/atsign-company/secondaries-scripts/pull/14 is reviewed.

**Comment by kumarnarendra701** [comment]
@cpswan @cconstab @gkc -Currently, the script makes the connection via SSH to LB and it routes to  Hornet1 to spin up secondaries. So as per my understanding of the below points, I need to work.
1. Integrate new script on Buzz.
2. Change LB backend to new Swarm, so that secondaries can spinup on new swarm (We can make swarm0001-01 as primary and cut new traffic on hornet-01 )
3. Ashish need to set a new swarm domain entry to root so that new secondaries will start using the new domain
Please confirm and share your feedback

**Comment by cpswan** [comment]
s the new multi domain scripts rely on /root/.env to get $DOMAIN you just need to SSH to the $DOMAIN-01 host and run from there. The scripts will pick up $DOMAIN from .env and create certs and config files accordingly.

1. You can certainly try the new scripts on Buzz - just make sure to create the appropriate /root/.env file (there's a template in the repo)
2. I'm not entirely sure what you mean by LB here? For each cluster we will create a load balancer on NS1 that will point to the worker nodes in the cluster. They will be of the form $DOMAIN.lb.atsign.zone
3. Ashish will need to keep track of which secondaries are going onto which cluster, and the corresponding domain name associated with that. This was discussed on the architecture call earlier. For now we expect to start filling up swarm0001, and once that's looking full we'll spin up swarm0002 etc. The analogy I used is it's like coal trucks being filled up underneath a hopper.

**Comment by kumarnarendra701** [comment]
@cpswan - Below Updates
1.  New swarm0001 is live and verified by creating/deleting a few test secondaries.
2. Deployed new scripts on buzz and prod.

**Comment by gkc** [comment]
This has been working for the past week
