### ISSUE TITLE
forText notifications with StrategyEnum.latest do not provide just the latest notification.

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#911]
**Describe the bug**
Old notifications appearing as atsign connects

**To Reproduce**
1. First I run the MWC demo code and clients (using the iot-expo-colin branch)
2. Then I sent some readings
3. And then 'switched atSign to an atsign that also was sent the notifications
4. Old notifications appear on reconnect
5. These old notifcations can build up if the atSign is not used for a while and notifications have come in. Resulting in an unrecoverable state in the worst case

**Expected behavior**
Notifications should not be stored and only new notifcations be sent onward 

**Screenshots**

https://user-images.githubusercontent.com/6131216/190032985-70f4d475-adc6-40b0-a2cc-956d8e679f27.mp4

Video'd session was using the trunk branch for the secondary (in my dess infra)

**Were you using an atApplication when the bug was found?**
  - MWC Demo

**Additional context**
The video has more context. This is P1 as it can lead to bad things!

**Comment by sitaram-kalluri** [comment]
The root cause of the issue is when client comes online (back from offline),  irrespective of the notification strategy used the secondary server sends every notification received from the time interval of last sent notification date-time.

Had a discussion with @VJag and following the approach to fix the issue:
1. Send the notification strategy and the notifier and the latest-N to the receiver atSign
2. When writing notifications back to the client (receiver's client), if the strategy is 'latest' write only the latest 'N' notifications to the monitor and ignore the rest.

**Comment by cpswan** [comment]
Surely this should be mediated by the TTL for the notifications. If a notification still has time to live, then it gets passed on, else the TLL has expired, and the notification is dropped.

Of course this still potentially leads to a problem where the sender doesn't set correct TTL, causing notifications to stack up, which is where we need an approach to dealing with the deluge. But none of this is new, these are all problems that have been affecting store and forward and other forms of messaging middleware for decades; so let's not reinvent the wheel.

**Comment by sitaram-kalluri** [comment]
@cconstab : Please use the following branch in at_client repo to test the changes: [ignore_offline_notifications](https://github.com/atsign-foundation/at_client_sdk/tree/ignore_offline_notifications)
